import type { DashboardPayload } from "./contracts";

export const dashboardFixture: DashboardPayload = {
  merchant: {
    id: "m_1007",
    name: "MEGURO KITCHEN LAB",
    plan: "Growth",
    terminalHealth: 98,
    todaySales: 742800,
    yesterdaySales: 681400,
    activeTables: 18,
    queueLength: 7,
    visitorCount: 386,
  },
  orders: [
    {
      id: "ORD-1048",
      table: "A12",
      guests: 4,
      items: ["Seasonal lunch set", "Iced coffee", "Kids plate"],
      status: "cooking",
      amount: 8420,
      openedAt: "11:42",
      etaMinutes: 8,
    },
    {
      id: "ORD-1049",
      table: "B03",
      guests: 2,
      items: ["USEN burger", "Craft cola"],
      status: "ready",
      amount: 3960,
      openedAt: "11:49",
      etaMinutes: 0,
    },
    {
      id: "ORD-1050",
      table: "C07",
      guests: 3,
      items: ["Pasta set", "Dessert plate", "Hot tea"],
      status: "served",
      amount: 6210,
      openedAt: "12:02",
      etaMinutes: 0,
    },
    {
      id: "ORD-1051",
      table: "TAKEOUT",
      guests: 1,
      items: ["Salad bowl", "Sparkling water"],
      status: "new",
      amount: 1780,
      openedAt: "12:06",
      etaMinutes: 12,
    },
  ],
  tables: [
    {
      id: "A01",
      zone: "Main",
      seats: 2,
      status: "available",
      customerNo: null,
      orderId: null,
      amount: 0,
      openedAt: null,
      lastAction: "Sanitized 3 min ago",
    },
    {
      id: "A12",
      zone: "Main",
      seats: 4,
      status: "ordering",
      customerNo: "G-238",
      orderId: "ORD-1048",
      amount: 8420,
      openedAt: "11:42",
      lastAction: "追加注文 2 min ago",
    },
    {
      id: "B03",
      zone: "Window",
      seats: 2,
      status: "checkout",
      customerNo: "G-241",
      orderId: "ORD-1049",
      amount: 3960,
      openedAt: "11:49",
      lastAction: "会計呼出中",
    },
    {
      id: "B08",
      zone: "Window",
      seats: 4,
      status: "reserved",
      customerNo: "R-119",
      orderId: null,
      amount: 0,
      openedAt: "12:30",
      lastAction: "Reservation hold",
    },
    {
      id: "C07",
      zone: "Terrace",
      seats: 6,
      status: "seated",
      customerNo: "G-245",
      orderId: "ORD-1050",
      amount: 6210,
      openedAt: "12:02",
      lastAction: "Water served",
    },
    {
      id: "C11",
      zone: "Terrace",
      seats: 2,
      status: "cleaning",
      customerNo: null,
      orderId: null,
      amount: 0,
      openedAt: null,
      lastAction: "Clear down",
    },
  ],
  checkouts: [
    {
      id: "CHK-5103",
      table: "B03",
      customerNo: "G-241",
      subtotal: 3600,
      tax: 360,
      discount: 0,
      total: 3960,
      method: "qr",
      status: "ready",
      requestedAt: "12:08",
    },
    {
      id: "CHK-5104",
      table: "A12",
      customerNo: "G-238",
      subtotal: 7900,
      tax: 790,
      discount: 270,
      total: 8420,
      method: "card",
      status: "processing",
      requestedAt: "12:10",
    },
    {
      id: "CHK-5105",
      table: "TAKEOUT",
      customerNo: "T-078",
      subtotal: 1650,
      tax: 165,
      discount: 35,
      total: 1780,
      method: "cash",
      status: "draft",
      requestedAt: "12:12",
    },
  ],
  transactions: [
    {
      id: "PAY-92031",
      orderId: "ORD-1045",
      method: "card",
      status: "settled",
      amount: 12890,
      brand: "Visa",
      capturedAt: "12:01",
      riskScore: 8,
    },
    {
      id: "PAY-92032",
      orderId: "ORD-1047",
      method: "qr",
      status: "authorized",
      amount: 5840,
      brand: "PayPay",
      capturedAt: "12:04",
      riskScore: 12,
    },
    {
      id: "PAY-92033",
      orderId: "ORD-1048",
      method: "transport",
      status: "failed",
      amount: 8420,
      brand: "Suica",
      capturedAt: "12:07",
      riskScore: 61,
    },
    {
      id: "PAY-92034",
      orderId: "ORD-1044",
      method: "card",
      status: "refunding",
      amount: 2190,
      brand: "Mastercard",
      capturedAt: "12:09",
      riskScore: 24,
    },
  ],
  visitors: [
    { time: "09:00", visitors: 28, seats: 12, checkoutWait: 1 },
    { time: "10:00", visitors: 46, seats: 18, checkoutWait: 2 },
    { time: "11:00", visitors: 89, seats: 41, checkoutWait: 4 },
    { time: "12:00", visitors: 137, seats: 62, checkoutWait: 7 },
    { time: "13:00", visitors: 96, seats: 48, checkoutWait: 5 },
    { time: "14:00", visitors: 54, seats: 21, checkoutWait: 2 },
  ],
};
